### ISSUE TITLE
Can't clone on windows

### ISSUE THREAD

**Issue by realbcole** [WildMeOrg/houston#857]
Trying to work on a codex issue, but I get this error when cloning this repository:

$ git clone --recurse-submodules https://github.com/WildMeOrg/houston.git
Cloning into 'houston'...
remote: Enumerating objects: 34885, done.
remote: Counting objects: 100% (1237/1237), done.
remote: Compressing objects: 100% (354/354), done.
remote: Total 34885 (delta 954), reused 1065 (delta 880), pack-reused 33648
Receiving objects: 100% (34885/34885), 38.20 MiB | 36.36 MiB/s, done.
Resolving deltas: 100% (25924/25924), done.
error: invalid path 'tests/asset_groups/test-000/zebra_?_.jpg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by naknomum** [comment]
sorry you ran into this problem. bit of research and it seems like this is a fairly well-document problem, but one without a ton of simple solutions.  i did find [this thread on stackoverflow](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows/63742773) which _might_ offer some hints. if you are feeling adventurous, you might check it out and give some a try. i should be able to have access to a windows machine this weekend, and will be trying some of it myself.  will report back with what i find next week.

**Comment by TanyaStere42** [comment]
@realbcole we finally tracked down this issue ourselves. Turns out there was a test file that was blocking, so we have altered that test, got rid of the file, and now it's successfully cloning down to Windows.
Thanks for reporting! Sorry for the long resolution time
