### ISSUE TITLE
re-run ID api call fix

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#868]
Current state:

front end sends a parameter that alters the match set when a user re-runs ID from the sighting page; it needs to be removed

Desired state:
no change in user experience
https://github.com/WildMeOrg/codex-frontend/blob/develop/src/pages/sighting/identification/buildMatchingSetQuery.js#L62-L65 is no longer sent while generating a match set

**Can this change be verified in the UI?** No, but it can be verified in postman/console
api should respond with 200 (verifying json was valid) and (eventually) id job should finish.

**QA:**
- Verify the parameter is not sent
- Verify a 200 response
- Verify ID job finishes

**Investigation notes**
in the frontend ui for re-run identification (sighting page), some json data is created to send to the backend api.  part of this json will be an element like "must_not": {"match": {"encounter_guid": "_MACRO_annotation_encounter_guid "}}} — this should be removed so that it is no longer sent to the backend.

**Comment by naknomum** [comment]
this was fixed in frontend by [this PR](https://github.com/WildMeOrg/codex-frontend/pull/472/files).  (payload also confirmed correct on QA)
