### ISSUE TITLE
Autogenerate names/Codex ID - Codex ID to all individuals when turned on

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#878]
Context: arguments about names are a significant reason against collaboration within biology. People want to maintain the specific name they leverage in their personal catalogue.

By providing an automatically generated name that is associated with Codex specifically, we can promote Codex as a collaboration tool, as well as a catalogue solution, by providing a workspace with common shared nomenclature that does not threaten the name spaces used in individual catalogues.

## Resources

Final design: https://www.figma.com/file/CQlIlIp73EjmGKANvWzoIR/Codex%3A-Autogenerate-names?type=design&node-id=414-24333&mode=design&t=lL6As7KZvdqzLDeh-0

User Story:

- As a user of Codex with Codex ID in place, I can see a Codex ID on all individuals, including those created before Codex ID was turned on

QA:

- cannot turn on Codex ID without providing prefix for all species
- must provide distinct prefix for each species

**Comment by TanyaStere42** [comment]
depends on https://github.com/WildMeOrg/houston/issues/867

**Comment by naknomum** [comment]
_note:_ this will also populate names on individuals when an AutogeneratedName is **re-enabled** after being off for some time (during which individuals were created).

related method: `agn.populate_all_individuals()`
