### ISSUE TITLE
admin - keyword count

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#886]
## Context
Admins will need to have the context of a keyword's use when determining how to manage the keyword in the future

## User Story
/api/v1/keywords

- [ ] provides count of keyword's use (associations with annotations)

## Resources
Example of use:

![Image](https://user-images.githubusercontent.com/62726866/257334752-948489be-af10-4636-841c-a6cd9d522a05.png)

**Comment by Veda-Gogineni** [comment]
Hi @TanyaStere42, , I'm ready to work on this issue. Please assign it to me. Thanks!
