### ISSUE TITLE
sighting stage disconnect from match state

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#887]
## Context
Sighting has a Stage field, which is currently adjusted by either Sage/WBIA, or by the user indicating that a sighting is reviewed. This is overloaded and makes processing complicated and support difficult.

## User story
- [ ] Stage field needs to just be adjust be Sage/WBIA
- [ ] All additional functions need to have their own endpoints before Stage gets simplified

## verification
- nothing breaks when you commit

**Comment by naknomum** [comment]
related/remove? - `/api/v1/sightings/GUID/reviewed` endpoint

**Comment by naknomum** [comment]
notes from slack:

- have Sighting `review_time` updated instead via new `PATCH` on `match_state`
- `User.unprocessed_sightings()` now return Sightings which are not in _match state_ of `reviewed` or `unidentifiable`
