### ISSUE TITLE
Can't commit a sighting if an annotation was deleted from it

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/houston#906]
**Expected Behavior**
If an incorrect viewpoint is assigned, you can delete the annotation, add and assign a new one, and commit the sighting.

**Current Behavior**
If an incorrect viewpoint is assigned, deleting the annotation and adding a new one prevents the sighting from being committed. There is a grey image that may be behaving as a placeholder for the deleted annotation.

![Image](https://github.com/WildMeOrg/codex-frontend/assets/103530016/be49abd8-b070-412d-8b6d-cb75d5491a1f)

**QA Notes**
Anastasia tested this in QA server. [Once](https://qa.dyn.wildme.io/pending-sightings/19d9e1cb-7dd0-400c-a922-49b83ac5022c#individuals) with the user's image and a [second](https://qa.dyn.wildme.io/pending-sightings/97db2493-f4d2-4b0c-806a-85456810ca10#individuals) time with the same image but with the EXIF data stripped. I was able to replicate the issue with not being able to commit the results each time.

**Community Link**
email thread with Snail Codex folks to JH, Jon, Tanya, and Anastasia

**Comment by naknomum** [comment]
looks to be that this is due to FE calling `DELETE api/v1/annotations/GUID` (successfully) but this _not_ triggering a removal **from within the AssetGroupSighting** of the reference to this annotation.

**Comment by TanyaStere42** [comment]
Test case is to replicated reported issue:

- [ ] use image provided by customer
- [ ] upload image to QA server; use standard detection during submission
- [ ] When the "up" annotation is assigned, delete it and manually add "right" viewpoint.
- [ ] Assign annotation, verify there is no grey box "ghost" annotation simultaneously waiting to be assigned while being unassignable.
- [ ] Commit sighting

Success criteria: sighting is successfully committed

- Secondary test with additional image preferred but not required

**Comment by goddesswarship** [comment]
I was able to successfully test and commit sightings with both the user's image and my own.
