### ISSUE TITLE
individual search results needs last region

### ISSUE THREAD

**Issue by naknomum** [WildMeOrg/houston#907]
Individual search results needs last (i.e. most recent) region (`location_guid`) the individual was seen. That is to say, based on the _most recent sighting_ and its (sighting-level) region.

This corresponds to [frontend issue 562](https://github.com/WildMeOrg/codex-frontend/issues/562).

**Comment by naknomum** [comment]
confirmed with @erinz2020 that search results should return _region **name**_ (versus guid)

**Comment by TanyaStere42** [comment]
QA verified with FE implementation
