### ISSUE TITLE
individual search results needs last freeform location

### ISSUE THREAD

**Issue by naknomum** [WildMeOrg/houston#908]
Individual search results needs last (i.e. most recent) freeform location (`verbatimLocality`) the individual was seen. That is to say, based on the _most recent sighting_ and its (sighting-level) freeform location.

This corresponds to [frontend issue 563](https://github.com/WildMeOrg/codex-frontend/issues/563).

**Comment by TanyaStere42** [comment]
QA verified with FE implementation
