### ISSUE TITLE
individual search: partial search returns inconsistently

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#911]
## Expected Behavior
partial search results return consistently

## Current Behavior
There is some processing going on with individual search that causes it to return results inconsistently. I’ve tested with Phs prefix and CUPS prefix, and I’m getting different results between them, so I can’t really provide more detail

- in the manually assign ID on the sighting > animals tab, I get results for Phs and hs, but not phs
- in individual search using the individual name filter, I get results for hs, but no results for either Phs or phs
- in the quick search in the header, I get results for Phs and hs, but not phs

## Investigation notes
Anastasia: In Seal Codex I tried to manually assign an animal to an existing individual from the [sighting page](https://seals.wildme.org/sightings/8ef3e011-ac63-4aa9-9fd2-16f37a3ec019#individuals), but the search box to locate my individual shows no results for "phs415" or "Phs415" even though the individual exists [here](https://seals.wildme.org/individuals/c2a65e7b-d836-438a-bb01-a4bc3c8d5549).

<img width="822" alt="Screenshot 2023-08-29 at 10 17 27 AM" src="https://github.com/WildMeOrg/codex-frontend/assets/103530016/90091add-b462-4e7b-84bf-d6cc4f248bb0">

In Zebra Codex I tried to set a new relationship between a mother and a foal from this [individual page](https://zebra.wildme.org/individuals/fc31779c-e7f8-448e-a3f3-1301e68158b8). A search for "[F08_053_LAIK](https://zebra.wildme.org/individuals/018014d5-c030-4aa3-87a6-53d3f9452a79)" shows no results. If I search for "F08_0" or "F08_" only "F08_006_LAIK" appears as a suggestion.

<img width="1900" alt="no result" src="https://github.com/WildMeOrg/codex-frontend/assets/103530016/4e41e663-f892-48d5-b3e0-1da0d89dc55d">

<img width="1890" alt="partial result" src="https://github.com/WildMeOrg/codex-frontend/assets/103530016/ef07d16b-17e7-43dd-9f7c-80f2c2686f6e">

**Community link**
https://community.wildme.org/t/seal-codex-missing-individuals/2278
https://community.wildme.org/t/adding-relationship/2353

**Related drafts**
[Individual search: Can't sort by name or search a specific individual ](https://github.com/orgs/WildMeOrg/projects/4/views/1?pane=issue&itemId=34807791)
[Sighting search: inconsistent number of search results and long load times](https://github.com/orgs/WildMeOrg/projects/4/views/1?pane=issue&itemId=34510975)

Another bug found about searching:
when searching individual names on individual searching page, any individual with upper case letters in the name can't be found, no matter using the correct case or not. 
When doing QA please also check if this is fixed.

![1694106641014](https://github.com/WildMeOrg/codex-frontend/assets/99415659/25aea68a-0ba5-4c4e-a981-a02c62972403)
![1694106667503](https://github.com/WildMeOrg/codex-frontend/assets/99415659/aba7e369-d9ab-44ab-a55b-223237c621e6)

## QA Verification Checklist
- [ ] Consistent search results for partial individual name
  - [ ] baseline: work with BE to get a count of individuals for a given search term. note term and value in QA
  - [ ] search for term in Individual search in name filter. note value returned. should equal count
  - [ ] search for term in sighting search in name filter. note value returned. should equal count
  - [ ] search for term in "match individual" on an individual that does not contain the term in their name. note value returned. should equal count
  - [ ] search for term in "match individual" on an individual that DOES contain the term in their name. note value returned, should equal count-1
- [ ] Repeat the above test for the following conditions:
  - [ ] all uppercase term
  - [ ] all lowercase term
  - [ ] mixed case term
  - [ ] mixed character term (ex above, phs could be tested as hs-0)
- [ ] Make note of time it takes for the results to load (reporting only, no failure criteria)

**Comment by goddesswarship** [comment]
QA notes: Baseline term "cups" verified with BE that number in QA server is 10. This matches the number that comes up in an individual search.

When searching for mixed characters such as "ps-0" or "cups-0" (and with different combinations of all caps and mixed case), only 6 results appear in an individual search, 6 results appear for a "match individual" search on an individual that doesn't contain the term in its name, and 5 results appear in a "match individual" search on an individual that does contain the term in its name.
