### ISSUE TITLE
Sighting search: inconsistent number of search results and long load times

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#925]
**Expected Behavior**
If you search sightings by owner, all available sightings for that user are displayed quickly.

**Current Behavior**
If you search sightings by owner, the number of results vary and the results take a long time to populate. Sometimes there will be 0 results for that user, 8 results, or 400+ results. The searches in the first 2 screenshots below were performed on the same day. The third was done 3 days later.

![Image](https://user-images.githubusercontent.com/103530016/256948560-b0fa2511-7276-45ee-a6c2-e3c38032c406.png)

![Image](https://user-images.githubusercontent.com/103530016/256948591-e4f9657a-31e5-4877-913e-5cdde5836baf.png)

![Image](https://user-images.githubusercontent.com/103530016/257301507-efb2be78-b0e0-4664-a95d-9f1dcf491f5a.png)

**Community Link**
https://community.wildme.org/t/missing-sightings-in-codex/2265

**QA Notes**
Anastasia: This did not appear to be related to a browser cache issue. This may be related to [issue #515](https://github.com/orgs/WildMeOrg/projects/4/views/1?pane=issue&itemId=28968024). Further testing needed to see if other sighting search ticket fixes have resolved this.

**Comment by TanyaStere42** [comment]
Believed to be solved with [issue #515](https://github.com/orgs/WildMeOrg/projects/4/views/1?pane=issue&itemId=28968024). Need to test on production for final confirmation.

**Comment by goddesswarship** [comment]
Tested Individual search and Sighting search in Zebra and Seal Codex. The number of search results was consistent in each test.
