### ISSUE TITLE
Fold export permissions into collaboration hierarchy

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/houston#932]
## Context
Permissions need to be streamlined and simplified for those hosting their own instances, and to ensure data access is as expected in the collaborative platform

##User Story
- As a user creating/editing a collaboration, I can request export access. Hierarchy goes View > Export > Edit
    - As a user with view collaboration with another user, I can see the information a user has in-platform. Matching is available at this level
    - As a user with export collaboration with another user, I am able to export their data from the platform leveraging any export format. [currently will be tested with animal, sighting, and individual general exports]
    - As a user with edit collaboration with another user, I can edit the information that the other user has submitted/is owner of in the platform.

## Related Stories
#933 
#934 
[FE#604](https://github.com/WildMeOrg/codex-frontend/issues/604)

**Comment by naknomum** [comment]
this kind of opens up a can of worms (which we have kicked down the road), namely _permissions on **searching**_. it is technically a little loose now, and probably should be addressed along with this issue. that is to say, exporting is now tied to "search results", so if we are going to have this pairwise/collaboration export concept, we need to have the search results reflect the same reality.

put another way, if a user searches and gets N results, they should expect that exporting from there gets them N results in the exported data (or at least have some way to know which M of the N will be exported).

**Comment by naknomum** [comment]
also: does this imply the removal of the **export role** for users?

**Comment by TanyaStere42** [comment]
A lot of questions here. For the explicit question "does this imply the removal of the export role" #933 That is explicitly covered.

**Comment by TanyaStere42** [comment]
The fallout of the search question:
Search displays results that a user does not have access to because it encourages organic discovery. We can add a detail of this in the export UI and provide the total number that were exported as part of the confirmation message. M and N do not need to match and there is not an expectation that they do, except for those with full system access.

**Comment by naknomum** [comment]
> The fallout of the search question: Search displays results that a user does not have access to because it encourages organic discovery. We can add a detail of this in the export UI and provide the total number that were exported as part of the confirmation message. M and N do not need to match and there is not an expectation that they do, except for those with full system access.

this sound reasonable; kinda what i was expecting/hoping. so it _will_ need a slight (?) revamp of search to include (roughly speaking) a boolean on each item for "does the searching user have full access to this item".
